apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
        - name: app
          image: gabrielfilomeno/hello-health:0.1
          ports:
            - containerPort: 8080